site_name: The DDS Way
site_description: 'DDS-Way'
site_author: 'DDS'
docs_dir: docs/
repo_name: 'defencedigital/dds-way'
repo_url: 'https://github.com/defencedigital/dds-way'
nav:
    - The DDS Way: index.md
    - Service Manual Test: servicemanualtest.md
    - Onboarding: onboarding.md
    - Software development: softwaredevelopment.md
    - Version control and deployments: versioncontroldeployments.md
    - Hosting and infrastructure: hostinginfrastructure.md
    - Logging, monitoring and alerting: loggingmonitoringalerting.md
    - Operating a service: operatingservice.md
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: deep purple